name: Deploy to AWS S3 Vite
on:
  push:
    branches:
      - main
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: npm install

      - name: Build for Production or Staging
        run: |
          if [ ${{ github.ref }} = 'refs/heads/main' ]; then
            npm run build
          elif [ "${{ github.ref }}" == "refs/heads/staging" ]; then
            npm run build:staging
          else
            echo "Not building"
          fi

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          aws-region: ap-south-1

      - name: Deploy to S3
        run: |
          if [ ${{ github.ref }} = 'refs/heads/main' ]; then
            aws s3 sync dist/ s3://mugu-configurator --delete
          elif [ "${{ github.ref }}" == "refs/heads/staging" ]; then
            aws s3 sync dist/ s3://mugu-configurator-staging --delete
          else
            echo "Not deploying"
          fi
